### ISSUE TITLE
Game Crashes During Combat After Recent Update

### ISSUE THREAD

**Issue by RhoGit** [FFXIV-CombatReborn/RotationSolverReborn#371]
A few hours ago, I installed an update that was offered to me. Since then, the game has been crashing sporadically, but only during combat, not every time I start it. 'Dalamud' is generating a log file called 'crash-20240918213231.tspack.'

I'm unsure if it's a good idea to upload the log file here, so I wanted to report the issue like this for now.

**Comment by nrwbond** [comment]
Same here. Strack trace:

Unhandled native exception occurred at ffxiv_dx11.exe+DF09D	(sub_1400DEE40+0x25D)
Code: C0000005
Dump at: C:\Users\******\AppData\Roaming\XIVLauncher\dalamud_appcrash_20240918_221125_086_17276.dmp
System Time: 2024-09-18 20:11:26.1652625

   at RotationSolver.Basic.DataCenter.<>c.<get_FriendlyNPCMembers>b__209_0(IBattleChara obj)
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at RotationSolver.Basic.DataCenter.get_FriendlyNPCMembers()
   at RotationSolver.Updaters.StateUpdater.StatusFromAutomatic()
   at RotationSolver.Updaters.StateUpdater.UpdateState()
   at RotationSolver.Updaters.MajorUpdater.UpdateWork()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by nrwbond** [comment]
Is there a way to downgrade to the last known good version from yesterday?

**Comment by Limiana** [comment]
https://github.com/FFXIV-CombatReborn/RotationSolverReborn/blob/main/RotationSolver.Basic/Helpers/ObjectHelper.cs#L169
this function can't be called from different thread as it accesses non-singleton properties of gameobjects
https://github.com/FFXIV-CombatReborn/RotationSolverReborn/blob/main/RotationSolver/Updaters/MajorUpdater.cs#L114
in general, accessing game memory from different thread is very delicate
the object table itself is singleton and you can access it, though it's possible you'll get stale or invalid data, but any time you need to follow pointer (or call game function that follows pointer) that has to be done only in main game thread

**Comment by LTS-FFXIV** [comment]
fixed in .90

**Comment by nrwbond** [comment]
thank you for the quick fix <3
